#!/bin/bash -xeu

# cgroups のインストール
sudo -E apt-get update -y
sudo -E apt-get install -y cgroup-bin cgroup-tools

# cgroups 動作確認用の stress コマンドインストール
sudo -E apt-get install -y stress

# cgrules.conf をPAMで適用する libpam-cgroup のインストール
sudo -E apt-get install -y libpam-cgroup
sudo sh -c "cat >> /etc/pam.d/common-session" <<EOF
session optional        pam_cgroup.so
EOF

# grub.conf 書き換え(http://rolk.github.io/2015/04/20/slurm-cluster)
sudo sed -i 's,\(^GRUB_CMDLINE_LINUX_DEFAULT\)=\"\(.*\)",\1=\"\2 cgroup_enable=memory swapaccount=1\",' /etc/default/grub
sudo update-grub

# cgroups 設定
sudo sh -c "cat > /etc/cgconfig.conf" <<EOF
group slurm {
  cpuset {
    cpuset.cpus = "0";
    cpuset.cpu_exclusive = "1";
  }
}
group other {
  cpuset {
    cpuset.cpus = "1";
  }
}
EOF

sudo sh -c "cat > /etc/cgrules.conf" <<EOF
#<user/group:bin> <controller(s)>      <cgroup>
root              cpu,cpuset,memory    /
slurm             cpu,cpuset,memory    /slurm
mysql             cpu,cpuset,memory    /slurm
munge             cpu,cpuset,memory    /slurm
*                 cpu,cpuset,memory    /other
EOF

sudo cp /usr/share/doc/cgroup-tools/examples/cgred.conf /etc/

# cgconfig.conf 設定反映用 systemd
sudo sh -c "cat > /etc/systemd/system/cgconfigparser.service" <<EOF
[Unit]
Description=cgroup config parser
After=network.target

[Service]
User=root
Group=root
ExecStart=/usr/sbin/cgconfigparser -l /etc/cgconfig.conf
Type=oneshot

[Install]
WantedBy=multi-user.target
EOF

# cgrulesengd 管理用 systemd
sudo sh -c "cat > /etc/systemd/system/cgrulesengd.service" <<EOF
[Unit]
Description=cgroup rules generator
After=network.target cgconfigparser.service

[Service]
User=root
Group=root
Type=forking
EnvironmentFile=-/etc/cgred.conf
ExecStart=/usr/sbin/cgrulesengd
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

# systemd 登録
sudo systemctl daemon-reload
sudo systemctl enable cgconfigparser
sudo systemctl enable cgrulesengd
sudo systemctl start cgconfigparser
sudo systemctl start cgrulesengd

# munge インストール
sudo -E apt-get install -y munge
sudo systemctl enable munge
sudo systemctl start munge

# slurm インストール 
sudo -E apt-get install -y slurm-wlm
sudo sh -c "cat > /etc/slurm-llnl/slurm.conf" <<EOF
# slurm.conf file generated by configurator easy.html.
# Put this file on all nodes of your cluster.
# See the slurm.conf man page for more information.
#
ControlMachine=localhost
ControlAddr=127.0.0.1
#
#MailProg=/bin/mail
MpiDefault=none
#MpiParams=ports=#-#
ProctrackType=proctrack/pgid
ReturnToService=1
SlurmctldPidFile=/var/run/slurm-llnl/slurmctld.pid
#SlurmctldPort=6817
SlurmdPidFile=/var/run/slurm-llnl/slurmd.pid
#SlurmdPort=6818
SlurmdSpoolDir=/var/lib/slurm-llnl/slurmd
SlurmUser=slurm
#SlurmdUser=root
StateSaveLocation=/var/lib/slurm-llnl/slurmctld
SwitchType=switch/none
TaskPlugin=task/none
#
#
# TIMERS
#KillWait=30
#MinJobAge=300
#SlurmctldTimeout=120
#SlurmdTimeout=300
#
#
# SCHEDULING
FastSchedule=1
SchedulerType=sched/backfill
#SchedulerPort=7321
SelectType=select/linear
#
#
# LOGGING AND ACCOUNTING
AccountingStorageType=accounting_storage/none
ClusterName=cluster
#JobAcctGatherFrequency=30
JobAcctGatherType=jobacct_gather/none
#SlurmctldDebug=3
SlurmctldLogFile=/var/log/slurm-llnl/slurmctld.log
#SlurmdDebug=3
SlurmdLogFile=/var/log/slurm-llnl/slurmd.log
#
#
# COMPUTE NODES
NodeName=localhost NodeAddr=127.0.0.1 CPUs=1 State=UNKNOWN
PartitionName=debug Nodes=localhost Default=YES MaxTime=INFINITE State=UP
EOF

sudo systemctl enable slurmctld
sudo systemctl start slurmctld
sudo systemctl enable slurmd
sudo systemctl start slurmd

